async (input) => {
  const params = new URLSearchParams()
  if (input.name !== undefined && input.name !== null)
    params.set('name', input.name)
  if (input.desc !== undefined && input.desc !== null)
    params.set('desc', input.desc)
  if (input.due !== undefined)
    params.set('due', input.due === null ? '' : input.due)
  if (input.dueComplete !== undefined && input.dueComplete !== null)
    params.set('dueComplete', String(input.dueComplete))
  if (input.closed !== undefined && input.closed !== null)
    params.set('closed', String(input.closed))
  if (input.idList !== undefined && input.idList !== null)
    params.set('idList', input.idList)
  if (input.pos !== undefined && input.pos !== null)
    params.set('pos', String(input.pos))
  const res = await integration.fetch(`/cards/${encodeURIComponent(input.cardId)}?${params.toString()}`, { method: 'PUT' })
  return await res.json()
}
